### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by LorenzoSapora** [alberto-bottarini/nova-exclusive-fields#1]
Ciao Alberto,

First of all, interesting idea for a package, but I am not quite following the use case for this.

Is it to reset all other values in a column? So, for example:
```csv
// users table
id,name,is_admin
1,lorenzo,0
2,alberto,1
3,foo,0
4,bar,0
```
where running this package (example: `update users set is_admin=1 where id=1`) would result in:

```csv
// users table
id,name,is_admin
1,lorenzo,1
2,alberto,0
3,foo,0
4,bar,0
```

**Comment by alberto-bottarini** [comment]
Yes. This is a valid use case.
It runs this query, only if the updated resource is saved correctly:

`update users set is_admin = 0 where id <> 1`

I would like to create some other fields, for example a ExclusiveSelect in order to have only a single record for each options.
Try to image for example a list of products and you would like to pick three of them to fill three exclusive spots in homepage.

**Comment by LorenzoSapora** [comment]
Excellent, thank you. I look forward to seeing your progress on this project.
